---
- name: Playbook to create an AMI from an existing EC2 instance
  hosts: all
  gather_facts: false

  tasks:

    - name: Create a new AMI from an EC2 Instance
      amazon.aws.ec2_ami:
        instance_id: "{{ aws_ec2_instance_id }}"
        region: '{{ aws_ec2_instance_region }}'
        name: WAG-New-Gold-Image
        tags:
          Name: New-Gold-Image
      register: ami_creation_output

    - name: Dump
      ansible.builtin.debug:
        var: ami_creation_output
