---
- name: A playbook to start customizations to our AWS instance
  hosts: all
  gather_facts: false
  become: true

  tasks:

    - name: Set the MOTD
      ansible.builtin.copy:
        content: |
          "Welcome to {{ aws_ec2_inventory_name }}!
           This host is managed by Ansible! Have a great day!
             __  __                                  _   ____
            |  \/  | __ _ _ __   __ _  __ _  ___  __| | | __ ) _   _
            | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \/ _` | |  _ \| | | |
            | |  | | (_| | | | | (_| | (_| |  __/ (_| | | |_) | |_| |
            |_|  |_|\__,_|_| |_|\__,_|\__, |\___|\__,_| |____/ \__, |
               _              _ _    |___/   _                 |___/
              / \   _ __  ___(_) |__ | | ___| |
             / _ \ | '_ \/ __| | '_ \| |/ _ \ |
            / ___ \| | | \__ \ | |_) | |  __/_|
           /_/   \_\_| |_|___/_|_.__/|_|\___(_)"
        dest: /etc/motd
        owner: root
        group: root
        mode: '644'
      when:
        - inventory_hostname == aws_ec2_inventory_name

    - name: Install the Tree package
      ansible.builtin.dnf:
        name: tree
        state: present
      when:
        - inventory_hostname == aws_ec2_inventory_name
